var annotated_dup =
[
    [ "alt", "d6/d94/namespacealt.html", "d6/d94/namespacealt" ],
    [ "LeakCheck", "dc/de5/namespace_leak_check.html", "dc/de5/namespace_leak_check" ],
    [ "oss", "d2/d84/namespaceoss.html", "d2/d84/namespaceoss" ],
    [ "PerfCheck", "d1/d3d/namespace_perf_check.html", "d1/d3d/namespace_perf_check" ],
    [ "picojson", "d4/d58/namespacepicojson.html", "d4/d58/namespacepicojson" ],
    [ "WindowsLibraryTest", "db/d5a/namespace_windows_library_test.html", "db/d5a/namespace_windows_library_test" ],
    [ "_container", "d4/d3c/struct__container.html", "d4/d3c/struct__container" ],
    [ "fts5_api", "da/d3a/structfts5__api.html", "da/d3a/structfts5__api" ],
    [ "fts5_tokenizer", "d7/d6f/structfts5__tokenizer.html", "d7/d6f/structfts5__tokenizer" ],
    [ "Fts5ExtensionApi", "d8/d3b/struct_fts5_extension_api.html", "d8/d3b/struct_fts5_extension_api" ],
    [ "Fts5PhraseIter", "da/d31/struct_fts5_phrase_iter.html", "da/d31/struct_fts5_phrase_iter" ],
    [ "sqlite3_file", "db/db0/structsqlite3__file.html", "db/db0/structsqlite3__file" ],
    [ "sqlite3_index_info", "d2/d4a/structsqlite3__index__info.html", "d2/d4a/structsqlite3__index__info" ],
    [ "sqlite3_io_methods", "d9/df3/structsqlite3__io__methods.html", "d9/df3/structsqlite3__io__methods" ],
    [ "sqlite3_mem_methods", "d4/d9a/structsqlite3__mem__methods.html", "d4/d9a/structsqlite3__mem__methods" ],
    [ "sqlite3_module", "dd/de4/structsqlite3__module.html", "dd/de4/structsqlite3__module" ],
    [ "sqlite3_mutex_methods", "da/de2/structsqlite3__mutex__methods.html", "da/de2/structsqlite3__mutex__methods" ],
    [ "sqlite3_pcache_methods", "d7/d71/structsqlite3__pcache__methods.html", "d7/d71/structsqlite3__pcache__methods" ],
    [ "sqlite3_pcache_methods2", "df/dca/structsqlite3__pcache__methods2.html", "df/dca/structsqlite3__pcache__methods2" ],
    [ "sqlite3_pcache_page", "d8/d72/structsqlite3__pcache__page.html", "d8/d72/structsqlite3__pcache__page" ],
    [ "sqlite3_rtree_geometry", "d8/d14/structsqlite3__rtree__geometry.html", "d8/d14/structsqlite3__rtree__geometry" ],
    [ "sqlite3_rtree_query_info", "d9/df9/structsqlite3__rtree__query__info.html", "d9/df9/structsqlite3__rtree__query__info" ],
    [ "sqlite3_snapshot", "db/db4/structsqlite3__snapshot.html", "db/db4/structsqlite3__snapshot" ],
    [ "sqlite3_vfs", "d3/d36/structsqlite3__vfs.html", "d3/d36/structsqlite3__vfs" ],
    [ "sqlite3_vtab", "d3/d12/structsqlite3__vtab.html", "d3/d12/structsqlite3__vtab" ],
    [ "sqlite3_vtab_cursor", "d3/d17/structsqlite3__vtab__cursor.html", "d3/d17/structsqlite3__vtab__cursor" ],
    [ "WatchDogData", "de/d1b/struct_watch_dog_data.html", null ]
];